# Generated by Django 2.2 on 2021-05-11 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_affiliation', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=150)),
                ('user_address', models.CharField(max_length=150)),
                ('user_city', models.CharField(max_length=50)),
                ('user_state', models.CharField(max_length=2)),
                ('user_zipcode', models.IntegerField(max_length=5)),
                ('password', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('animal', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=1)),
                ('pet_city', models.CharField(max_length=50)),
                ('pet_state', models.CharField(max_length=2)),
                ('pet_zip_code', models.IntegerField(max_length=5)),
                ('pet_affiliation', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adopted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopted_pet', to='adopt_app.User')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='adopt_app.User')),
                ('user_fav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_pets', to='adopt_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Adopt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopt_fname', models.CharField(max_length=100)),
                ('adopt_lname', models.CharField(max_length=100)),
                ('adopt_email', models.CharField(max_length=150)),
                ('adopt_address', models.CharField(max_length=150)),
                ('adopt_city', models.CharField(max_length=50)),
                ('adopt_state', models.CharField(max_length=2)),
                ('adopt_zipcode', models.IntegerField(max_length=5)),
                ('home', models.TextField()),
                ('other_pets', models.CharField(max_length=50)),
                ('children', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet_adopt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_adopts', to='adopt_app.Pet')),
                ('user_adopt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_adopts', to='adopt_app.User')),
            ],
        ),
    ]
