# Generated by Django 2.2 on 2021-05-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopt',
            name='adopt_zipcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_zip_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_zipcode',
            field=models.IntegerField(),
        ),
    ]
