# Generated by Django 2.2 on 2021-05-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt_app', '0004_auto_20210513_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopt',
            name='pet_adopt',
        ),
        migrations.AddField(
            model_name='adopt',
            name='pet_adopt',
            field=models.ManyToManyField(related_name='pet_adopts', to='adopt_app.User'),
        ),
        migrations.RemoveField(
            model_name='adopt',
            name='user_adopt',
        ),
        migrations.AddField(
            model_name='adopt',
            name='user_adopt',
            field=models.ManyToManyField(related_name='user_adopts', to='adopt_app.User'),
        ),
    ]
