# Generated by Django 2.2 on 2021-05-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt_app', '0005_auto_20210514_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopt',
            name='user_adopt',
        ),
        migrations.AddField(
            model_name='pet',
            name='user_adopt',
            field=models.ManyToManyField(related_name='user_adopts', to='adopt_app.User'),
        ),
    ]
